const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const testdata = new Schema({
  landingPageUrl: String,
  loyaltyPointsEnabled: Boolean,
  adId: String,
  isPLA: Boolean,
  productId: Number,
  product: String,
  productName: String,
  rating: Number,
  ratingCount: Number,
  isFastFashion: Boolean,
  futureDiscountedPrice: Number,
  futureDiscountStartDate: String,
  discount: Number,
  brand: String,
  searchImage: String,
  effectiveDiscountPercentageAfterTax: String,
  effectiveDiscountAmountAfterTax: Number,
  buyButtonWinnerSkuId: Number,
  buyButtonWinnerSellerPartnerId: Number,
  relatedStylesCount: Number,
  relatedStylesType: String,
  productVideos: Array,
  inventoryInfo: Array,
  sizes: String,
  images: Array,
  gender: String,
  primaryColour: String,
  discountLabel: String,
  discountDisplayLabel: String,
  additionalInfo: String,
  category: String,
  mrp: Number,
  price: Number,
  advanceOrderTag: String,
  colorVariantAvailable: Boolean,
  productimagetag: String,
  listViews: Number,
  discountType: String,
  tdBxGyText: String,
  catalogDate: String,
  season: String,
  year: String,
  isPersonalised: Boolean,
  eorsPicksTag: String,
  personalizedCoupon: String,
  personalizedCouponValue: Number,
  productMeta: String,
  systemAttributes: Array,
  attributeTagsPriorityList: Array,
  preferredDeliveryTag: String,
});

module.exports = mongoose.model("fule", testdata);
